server:
  servlet:
    context-path: /booksale

spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/booksale
    username: springstudent
    password: springstudent

  jpa:
    properties:
      hibernate:
        format_sql: true



logging:
  level:
    org:
      hibernate:
        SQL: debug

    root: INFO
    org.springframework.security: DEBUG